EOI_WELCOME_MESSAGE: "EOI - Emprendimiento Juvenil"
EOI_PRIMARY_COLOR: "#7DB61A" # eoi green

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# EOI_FOOTER_NAV_LINKS: []
# EOI_FOOTER_LEGAL_LINKS: []
EOI_FOOTER_NAV_LINKS:
  - title: "Inico"
    url: "https://www.desafioempleojoven.es/"
  - title: "FAQ"
    url: "/faq"
  - title: "Expertos"
    url: "/experts"
  - title: "Contact"
    url: "https://docs.google.com/forms/d/e/1FAIpQLSexAs-2a_-o5XfUoyFxuN7r9Ak_rON5ECuXy99WY25NhcJXFg/viewform"
EOI_FOOTER_LEGAL_LINKS:
    - title: "Terminos de servicio"
      url: "/tos"
